<?php
$data = array (
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => 'test',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '48',
    'name' => 'test',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '水果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '1',
    'goods_num' => '7',
    'level' => 0,
    'id' => '1',
    'name' => '水果',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => 'sdf',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => 'sdf',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '干果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '1',
    'goods_num' => '2',
    'level' => 0,
    'id' => '45',
    'name' => '干果',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => 'rrr',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => 'rrr',
  ),
);
?>